language: node_js
node_js:
  - "lts/*"
env:
  - CODECOV_TOKEN="5cd42a17-ab8f-4d6b-991a-22476d2a4e92"
before_script:
  - npm install
script:
  - npm run build:esm
  - npm run build:cjs
  - npm run coverage
after_success:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search
